@startuml chromeでhttps://google.comを開く

participant chrome
entity DNS
entity webサーバ

chrome -> DNS: google.com名前解決
DNS --> chrome: 216.58.220.142
chrome -> webサーバ: 216.58.220.142:443に暗号化スイート送信し、SSL/TLS接続開始要求
note over DNS
    暗号化スイートには下記が含まれる
    - SSL version(基本TLS1.3)
    - サーバ認証アルゴリズム
    - 鍵交換アルゴリズム
    - 共通鍵暗号方式アルゴリズム
    - MACアルゴリズム
    - 圧縮アルゴリズム
end note
webサーバ --> chrome: 利用するアルゴリズム選択 + サーバ証明書(公開鍵)
note over DNS
    サーバ証明書とは具体的には？
    下記でSSL/TLS接続を確立し、証明書チェーン詳細を表示可能。
    openssl s_client -showcerts -connect google.com:443
end note
chrome -> chrome: 共通鍵生成
chrome -> chrome: 共通鍵をサーバの公開鍵で暗号化
chrome -> webサーバ: 公開鍵で暗号化した共通鍵
webサーバ -> webサーバ: 秘密鍵で共通鍵を復号
note over DNS
    以後は共通鍵で通信
end note

@enduml